[package]
name = "libav-sys"
version = "0.1.0"
authors = ["krishna chiatanya <kittuov@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
bindgen = "0.58.1"
